### ISSUE TITLE
Force round ball issue (again) - 10.8.0 build 1852

### ISSUE THREAD

**Issue by Crrispy** [vpinball/vpinball#1322]
Hello,

Thanks for the change to this, the ball is not anymore a small marble at the bottom of the playfield. Unfortunately, after a couple of tests in Window view mode (and also in legacy, same issue):
- Ball in the shooter lane is round and at realistic size (measured around 25x25 mm on screen, 42 inches), looks good.
- Unfortunately, once in play, it's not round anymore, but 25x21mm 🙄 X scale of the camera is 97% and YZ scale 87% . The ball is squished on the X axis in this example, although X scale is higher than YZ. But why is it round in the shooter lane which is almost at the same Y on the playfield than the flippers?....

VPX x64 Direct X, build 1852. Does this with any table. 

![20240109_191502](https://github.com/vpinball/vpinball/assets/28100190/d712054e-de97-4044-95ce-6b310f7a298e)

**Comment by francisdb** [comment]
What does the ball look like without anti stretch? Looks like it's overcompensating.
What are your cabinet player pov settings?

**Comment by francisdb** [comment]
Some screenshots taken on macos standalone for all options

Equal scaling no anti stretch
<img width="379" alt="image" src="https://github.com/vpinball/vpinball/assets/161305/79650fd3-ca7c-420e-aa32-d25d44742cdf">

Unequal scaling no anti stretch
<img width="379" alt="image" src="https://github.com/vpinball/vpinball/assets/161305/c0b17ae8-9cd8-4464-a75c-3f39bce21f1b">

Equal scaling anti stretch
<img width="379" alt="image" src="https://github.com/vpinball/vpinball/assets/161305/b0dc811d-75cd-4b51-aa1f-71fad06b9fa1">

Unequal scaling anti stretch
<img width="379" alt="image" src="https://github.com/vpinball/vpinball/assets/161305/d11526dc-1034-44f7-99d6-08b6797cf0d8">

**closeup**

left equal/no anti-stretch, center equal/anti-stretch, right unequal/anti-stretch
<img width="54" alt="image" src="https://github.com/vpinball/vpinball/assets/161305/c6d99914-8b92-4b64-8ad5-acbd5c658a0d"><img width="54" alt="image" src="https://github.com/vpinball/vpinball/assets/161305/56b18856-65ea-4431-be2d-2cce8b661f87"><img width="54" alt="image" src="https://github.com/vpinball/vpinball/assets/161305/078d6fbd-fcd7-4acf-8576-2f33d02a31bb">

**Conclusion**

* anti-stretch is messing up an un-stretched situation (equal scale)
* anti-stretch makes the ball a lot smaller in stretched situations

**Comment by Crrispy** [comment]
Thanks for this detailed report. You probably also have the ball properly round in the shooter lane in the "unequal/anti-stretch" scenario? This is strange.

**Comment by keithhov** [comment]
I get a more round ball by unchecking the "force round ball" option.    Similar ball behavior as above,  Ball shape is generaly more narrow left to right at top of tables.

**Comment by francisdb** [comment]
> You probably also have the ball properly round in the shooter lane in the "unequal/anti-stretch" scenario?

<img width="459" alt="image" src="https://github.com/vpinball/vpinball/assets/161305/9c7184a0-cfd7-4a77-804c-210c80421dd5">


first is in shooter lane, second on right flipper, third on left flipper, fourth on top left somewhere

<img width="50" alt="image" src="https://github.com/vpinball/vpinball/assets/161305/4f3007c8-396f-44cf-a8c6-4da56fd91b96"><img width="45" alt="image" src="https://github.com/vpinball/vpinball/assets/161305/0f40d742-fe27-41b2-87e3-a94dc1258620"><img width="45" alt="image" src="https://github.com/vpinball/vpinball/assets/161305/4fe7c458-b4d5-4e8b-8fcf-12b6cc7467b0"><img width="45" alt="image" src="https://github.com/vpinball/vpinball/assets/161305/01b79f32-0349-4611-8dd2-b7a559a6df8f">

**Comment by Crrispy** [comment]
Yep, but distance from player's eye if the ball is in the shooter lane or held on a flipper is not very different. I wonder if there are not 2 issues there, but not knowing how the code works, difficult to say. Is this all in the "ball.cpp/ball.h" part of the code?

**Comment by keithhov** [comment]
I don’t agree it should be skinny at the top,  especially on cabinet view… maybe slightly smaller but that’s just my opinion.   The ball is farther away from the player but also higher and closer on a vertical scale  so the change should be minimal. A square sign is square to me nearby or far way.   Currently it’s distracting to see the ball morph from narrow to round on the way down but it’s an improvement from what it was, the ball changes shape but it’s not a gradual change. I don’t play much of pinballx but the balls are always round regardless of position on playfield  and it seems right to me. I’m just glad there is some dialogue around it to get it better.   Sent from my iPhoneOn Jan 9, 2024, at 4:57 PM, Crrispy ***@***.***> wrote:﻿
Yep, but distance from player's eye if the ball is in the shooter lane or held on a flipper is not very different. I wonder if there are not 2 issues there, but not knowing how the code works, difficult to say. Is this all in the "ball.cpp/ball.h" part of the code?

**Comment by francisdb** [comment]
Looking at the code I wonder if this is not all way too complex? Why is projection involved?
Would looking at the scaling x vs yz not be enough to counter the stretch performed. Anything else is screen projection specific and should not be messed with? Or am I missing something?

pseudo code
```js
ball_x_scale = 1
if table_x_scale > table_yz_scale
  ball_x_scale = table_yz_scale / table_x_scale
// apply ball_x_scale to ball
```

If required this could also be done for  `table_x_scale < table_yz_scale` where the ball is shrunk on yz scale but that case is probably uncommon as it would indicate an ultrawide screen being in use.

https://github.com/vpinball/vpinball/blob/5672bc1131eed2a43430ac0f7c0716785f5fe82a/src/parts/ball.cpp#L173-L239

**Comment by Crrispy** [comment]
Same picture from my real pin 😉 For sure this is how it should look.

![20240110_112304](https://github.com/vpinball/vpinball/assets/28100190/f41ef93e-4047-4519-ab22-21642a80ae0b)

**Comment by Crrispy** [comment]
Well, I managed to compile VPX, I made a temporary supa dupa dirty fix, but at least I have a round ball now in play and quite realistically sized 😁

Lines 248 and 249:

antiStretch.x = 0.53f * (1.0f + sy / sx);
antiStretch.y = 0.45f * (1.0f + sx / sy);

I tested a dozen tables with antistretch on, both modern and old ones, result was always satisfying, probably because I have a quite similar X/YZ ratio on most tables. Of course, this is probably not the way it should be done, but at the moment, it works for me.

**Comment by keithhov** [comment]
nice, im going back to beta version before force roundball added... I can get a round ball but have to skinny the tables too much.

**Comment by timdeporte** [comment]
Yes, for me the new build is still totally unrealistic. I am repeating myself, I don’t see the point in changing the ball proportions dynamically when my head is practically hanging over the playfield. It is not that the ball at the top of the playfield screen is a mile away, giving a sharp angle. This perspective implementation is totally pointless for a pinball project. I don’t think anybody needs this, to be fair. Give us a ball that is perfectly round and has the same size, all the time. Or at least give us this option; PLEASE!

**Comment by timdeporte** [comment]
I didn’t hear any complaints on the previous settings in previous vpx versions. Users were very happy with the way it worked. In the latest builds all got messed up. Why change something that was working great? I am afraid that a lot of cabinet users will drop vpx 10.8 eventually if this implementation will be officially released.

**Comment by timdeporte** [comment]
Another thing. If the ball at the upper half of the screen would be bigger in size compared to a ball at the lower half of the screen, then we would need to make the table wider at the top also. Because otherwise the ball would not fit with its surroundings. This would look completely horrible.

**Comment by wrd1972** [comment]
Glad this is getting looked. 

Maybe I am in the minority and possibly all out wrong, but ideally, should the ball simply be perfectly round regardless of POV settings, or any other settings?

Would it be wrong to simply state that the ball should remain round and not be influenced by any setting period? If this were the case, my pincab would be very happy.

What am I missing here?

**Comment by wrd1972** [comment]
"For cabinet mode it makes sense for the ball to be stretched when further away from the player. That's just perspective doing it's work."

Don't understand how this could apply to a spherical object.

**Comment by francisdb** [comment]
I am talking about physical size when looking directly top-down on the screen. Of course what we all want is a round ball from where we are standing next to the screen.

Anyway. There is something wrong with the calculations as forcing a round ball without stretching the table gives us a squeezed ball.

**Comment by wrd1972** [comment]
Oh know I just saw that these settings are gone:

![Untitled](https://github.com/vpinball/vpinball/assets/119364072/78846b4d-77ab-43da-ba87-32b513078f88)

**Comment by keithhov** [comment]
Yep ,,,, no round ball for now . Hopefully it will get addressed.   I have gone back to the version before the change in ball. Sent from my iPhoneOn Jan 17, 2024, at 6:06 PM, wrd1972 ***@***.***> wrote:﻿
Oh know I just saw that these settings are gone:
Untitled.png (view on web)

**Comment by wrd1972** [comment]
Please give us back the settings above if round ball is far off.

**Comment by wrd1972** [comment]
Just installed 1856 and the balls are certainly more round than with 1855 IIRC. Anyone else able to confirm this?

**Comment by Loafmeister** [comment]
I do not know if this is useful or has been mentioned. If I play on the gl version in VR and have the anti-stretch (or whatever it’s called) option on, I get a stretched ball. But if I turn the option off , the ball is perfect.  Ie: the option is not required in VR

**Comment by keithhov** [comment]
I think a lot of the complaints are coming from those who are using cabinet mode. Sent from my iPhoneOn Jan 19, 2024, at 7:21 PM, Loafmeister ***@***.***> wrote:﻿
I do not know if this is useful or has been mentioned. If I play on the gl version in VR and have the anti-stretch (or whatever it’s called) option on, I get a stretched ball. But if I turn the option off , the ball is perfect.  Ie: the option is not required in VR

**Comment by Loafmeister** [comment]
I understand that. I’m just alluding to the programming and how with the option on it actually does the reverse in vr, it distorts the ball if the option is on and it stretches it if it’s off .  Maybe can help with understanding the issue when enabled for cab users.

**Comment by keithhov** [comment]
Gotcha, yeah it’s a mess .  Hopefully it’s gets right .  I went back to a version before all the roundness changes.    We should be able to have a round ball in vr and cabinet and desktop eventually. Sent from my iPhoneOn Jan 19, 2024, at 9:27 PM, Loafmeister ***@***.***> wrote:﻿
I understand that. I’m just alluding to the programming and how with the option on it actually does the reverse in vr, it distorts the ball if the option is on and it stretches it if it’s off .  Maybe can help with understanding the issue when enabled for cab users.

**Comment by wrd1972** [comment]
@Crrispy 

Hey question. You mentioned this a while back:
Lines 248 and 249:

antiStretch.x = 0.53f * (1.0f + sy / sx);
antiStretch.y = 0.45f * (1.0f + sx / sy);

Is this a manual way of entering settings to get the ball to the optimum round appearance? If yes, could you speak to this a bit more? I am hoping I can make custom adjustments to dial the ball in on my POV.

I really wish that the following was not removed because it allowed mt to have a 95% round ball regardless where it was positioned on the table:
![Untitled](https://github.com/vpinball/vpinball/assets/119364072/78846b4d-77ab-43da-ba87-32b513078f88)
It just did exactly what it was supposed to. But if you have an alternate way to key in some settings to do the same thing, I would be very grateful to better understand how to do that.

Thanks.

**Comment by Crrispy** [comment]
Hello,

I've just used this on a few 10.8 builds until the round ball was officially fixed in the standard code. It involved compiling VPX locally, but it was fun :-)

**Comment by Crrispy** [comment]
No hex editor there, it's in the source code, in ball.cpp. What's the issue you still have now with recent builds?

**Comment by wrd1972** [comment]
@Crrispy 
Okay, here we go. BTW, I am speaking to on FS view here since I play on my PinCab.

With the new windowed POV mode, I am now able to very accurate replicate the POV from my real pins at eye-level;, and translate that to the VP10 tables. I am very stickler for having the most accurate 1:1 scale appearance possible. The problem is, when I do use these settings, I get very bad ball stretch at the top of the table, or what I call egg-ball.

Below is a screen shot of the example table with the exact same POV settings I would use for any EM or early 80's table:
![image](https://github.com/vpinball/vpinball/assets/119364072/b2cc4dc2-9ece-440c-bf21-54e4e70f38e5)

The ball at the bottom of the PF looks decent, but at the top...well you can see its horribly stretched. Now I can reduce this effect if I change my "Player Y" from 40 down to 0, but then I lose my near picture perfect POV in favor of less ball Stretch.

**Comment by wrd1972** [comment]
Maybe I have read this thread wrong, but for FS view on a cab, there should be no need at all to stretch the ball like you see above. Since the ball is spherical, it does not suffer from perspective distortion like the PF image does as the POV is translated on the TV. It should simply be round at all times.

**Comment by wrd1972** [comment]
It appears to me that you can have a hundred people with 100 different POVs on there cabs, and depending on the "Y Player" setting, there can be more or less of this ball stretch.  It sure seems to me that the ball should remain perfectly round regardless of "Y player" setting or any setting for that matter when playing in FS view. Maybe there is a technical reason why this is not possible, but if there is than this is the root of the problem.

At the end of the day, hopefully there will be a solution to force the ball to be round at all times no matter what the settings. But currently the feature called "force round ball", certainly is not doing what its name implies, and in my case, it makes the situation worse.

Make sense?

**Comment by wrd1972** [comment]
I dont mean to be beating the dead horse here, but stretched ball is one of the leading gripes that folks have with VP when they play my cab. They always comment, whats wrong with the ball. I just hate to sacrifice my perfect POV in order to have a rounder ball because I absolutey love the new window POV feature. It is leaps and bounds better than the hackery we had before.

**Comment by wrd1972** [comment]
Oh BTW, the above table was tested with:
![image](https://github.com/vpinball/vpinball/assets/119364072/43293d2a-a574-4854-b228-7ea107568141)

**Comment by keithhov** [comment]
HI wrd1972.....try version 1888 if you have not done so, there was another
update to ball roundness... since then I have a round ball at the top of
tables regardless of POV.   Sometimes the ball seems to0 big on rails if z
height is high but much improved from older versions when the ball was
always skinny at the top of table.

**Comment by wrd1972** [comment]
@keithhov @Crrispy 
Ok here is what I see with rev 1888. Looks similar to rev 1894.
![image](https://github.com/vpinball/vpinball/assets/119364072/d8c9addd-4ed7-4228-804e-1a92a0aba241)

**Comment by francisdb** [comment]
One last attempt at explaining this, the two red balls have the same dimension, yet their projection on the screen is different.

<img width="610" alt="image" src="https://github.com/vpinball/vpinball/assets/161305/4d9d9e66-4a54-4275-b2b4-c80285631fa3">

**Comment by wrd1972** [comment]
Yes I will give you that after thinking it more. It just seems to me there cant be a "one-size-fits all" solution to address this issue. Based on ones preferred POV and the angle of the TV in the Pincab, the ball stretch can be more of an issue, or less of an issue, but In my case, its super noticeable with my preferred POV which certainly exacerbates the stretch.

I know I sound like a broken record here, but this can easily be fixed by having an adjustable setting that will reduce the vertical stretch as seen above. And yet again, we used to have this but it was recently removed. If I had that setting available to me in video preferences, I could reduce the setting by 30% and that would put the ball right where it needs to be like it once was.

Imo, we don't even need a setting to adjust the X-dimension of the ball. No point there at all. We only need the adjustment for the y-dimension.

![image](https://github.com/vpinball/vpinball/assets/119364072/f2333cdb-1c74-4836-be50-64d36ef3071f)

**Comment by wrd1972** [comment]
Here is a pic from my phone of the ball at my eye level. See its still stretched. Maybe I am just making too big a deal here. But I just wish I had that ability to reduce the Y-dimension like I used to be able to.
![image](https://github.com/vpinball/vpinball/assets/119364072/0b98365d-0fb8-4e49-b6ea-b0d7a17ab6ac)

**Comment by wrd1972** [comment]
For whatever reason, it just seems more glaring to me in person than the pic would suggest.

**Comment by keithhov** [comment]
Yeah still looks skinny at top… I don’t have that issue…maybe delete the table specific ini file for the table… I also had success with some tables/balls  looking odd when I changed versions of vpx so I deleted the pinballx file in the roaming folder… tables looked better after that. Currently all 200ish of my tables i have set force round ball and all are finally round…maybe a fraction of 1 percent narrower at the top but nothing like your picture.   Sent from my iPhoneOn Feb 27, 2024, at 6:13 PM, wrd1972 ***@***.***> wrote:﻿
For whatever reason, it just seems more glaring to me in person than the pic would suggest.

**Comment by timdeporte** [comment]
It is a discussion that is going on for quite some time, also in previous threads. In previous builds we had much worse perspective stretching, also at the bottom of the playfield. In the latest build this issue has been reduced quite a lot. Currently I have just a handful of tables where the ball is still not close to round. I agree with all comments, but the developers like to stick with this perspective stretching. I also don’t see the point.

**Comment by wrd1972** [comment]
Again thanks for the input. :)

I will end it with this. I am not suggesting that the current nominal settings be revised in any way since everyone is happy with them. I am ONLY asking for the y-dimension nominal setting to have an AVAILABLE ADJUSTMENT (similar to the other video adjustments) so that it can be fine tuned based on ones needs. Maybe this can be restored down the road if others become interested.

Everyone keep up the good work. This project is definitely heading in the right direction and improving every day.

**Comment by timdeporte** [comment]
I agree. It would be nice to be able to tweak the amount of perspective stretching via the vpx video settings or ini-file. The amount of stretching has been lowered to a more realistic level compared to earlier 10.8 builds. But still, not perfect. For me, it spoils certain tables on my cab. My choice for building a pincab and using vpx was the high realistic representation of a real pinball table. This angel lost its wings somehow.

**Comment by Crrispy** [comment]
Indeed, a table-specific parameter to adjust the stretching on the top (BTW, thanks for the picture explaining it perfectly) to everyone's taste would be interesting! Maybe we should create a specific feature request.

**Comment by wrd1972** [comment]
@Crrispy This makes a lot more sense the more that I think about it. I continue to see variation in ball stretch from table to table even when the POV settings are the exact same. I don't consider it unreasonable at all to have to dial in the ball stretch for every table if this promises a perfectly round ball at eye level regardless of POV and Pincab playfield TV slope.

In addition, this might simplify things down the road because maybe there won't be a need to keep re-engineering the ball-stretch algaryhtems as the engine evolves. Its now out of the devs hands and in the users hands just like the many other POV adjustments.

I think there should maybe be two adjustments. 
Adjustment 1.  This allows you to set the ball to perfectly round **TO THE EYE** at the bottom of the table.
Adjustment 2. This allows you to set the ball (with ball stretch applied/reduced) to perfectly round **TO THE EYE** at the top of the table.

This should hopefully give you a perfectly round ball **TO THE EYE** anywhere on the table for those who choose to fine-tune this. Others can choose to do nothing and they still have what they have now. Everybody wins!

**Comment by wrd1972** [comment]
Oh forgot to mention. You can place the ball at the top or the bottom in real time using pause or manual ball control, and then proceed to dial in the ball roundness setting in real time also. How easy is that?

**Comment by wrd1972** [comment]
@Crrispy I think I have figured this out. The reason I have consistent egg-ball to the eye is because I scale my tables with a POV of a 1:1 ratio, just as if your looking at a real pin. I have several real pins and I can 99% replicate the dead-nuts accurate 1:1 appearance just like I was looking at the real thing at eye level. I even scale the table so the ball is the same size as a real pinball. Now the down side to 1:1 scale POV is that the aprons will be pushed off the bottom of the screen, and I am totally fine with that.

I think a lot of other folks prefer to have the table aprons show, and they also prefer to fill the TV screen as much as possible. With this scaling, you wont have a 1:1 scaled appearance because you have now "squashed" the table on the vertical axis to fit the screen. So, I tested this POV and low and behold the ball appears perfectly round to my eye. Absolutely no complaint with the balls appearance with this POV.

I think its very safe to say that the ball stretch calculations in the VP10 engine CAN NOT EFFECTIVELY provide a round appearing ball to the eye for different ratio POVs. The calculation in the code cant be a one size fits all for all aspect ratios. I mean think about it. If the ball is stretched as the table is stretched, then its completely obvious why I see egg-ball with my 1:1 POV. Guys that prefer to fill the TV screen and show the aprons will not see this problem at all. 

Of course this leads me back to my wishing we had a an adjustment (like we used to have) in one form or another that allows me to fine tune the ball on the vatical axis.

**Comment by wrd1972** [comment]
@tommkell 
Hey, see my image above. Are you using that same 1:1 POV shown on the right?

**Comment by tommkell** [comment]
@wrd nope, i stretch the y axis to fill the screen then the x as much as i can get away with (before the circles on the playfield get too out of whack) Weird thing is if i update to the latest vpx i'll get eggy balls straight away without touching any settings, only way around it is to raise the z position or move the y position. Either way it flattens the table and loses that 3d look, so im sticking to 1795 for now.

**Comment by tommkell** [comment]
Don't know how you're not getting eggy balls with that layback/low z position? I have to raise my z  waaay higher than i'd like to prevent mega eggballs. Maybe its all down to the cabinet incline entry?? Mine is 7.4 degrees, what's yours at?

**Comment by wrd1972** [comment]
Mine is 12 degrees I think. That's one of those variables I was speaking to earlier.
