### ISSUE TITLE
Stern Nascar/NBAFB/CC tables hang after synchronization/semaphore changes

### ISSUE THREAD

**Issue by toxieainc** [vpinball/vpinball#1811]
..this must be due to the script, as it doesn't happen when using JPs table variant of Nascar.
Happens e.g. with https://www.vpforums.org/index.php?app=downloads&showfile=13101

**Comment by toxieainc** [comment]
@vbousquet Some other tables now also show weird behavior (extremely slow), like CC or NBAFB (both older variants), but when run with 10.7.X.

**Comment by toxieainc** [comment]
..and also happens with 10.8.0 and 10.8.1 (latest builds). So it must be the latest changes in PinMAME and/or the core script changes.
https://www.vpforums.org/index.php?app=downloads&showfile=11710 (NBAFB) 'hangs' with 10.7.X, crashes with 10.8.X (will file a separate issue for the latter).
https://www.vpforums.org/index.php?app=downloads&showfile=11670 (CC) 'hangs' with 10.7.X and 10.8.X.

**Comment by vbousquet** [comment]
I had a first look at NBA but was unable to reproduce. There was a bug in 10.8.1 which is now fixed (we pushed the more or less same fix at the same time :) ) but I can't get the table to hang. Maybe some initialize memory access that breaks things. Will have to find some more time on this one

**Comment by toxieainc** [comment]
It seems to be related to setting the TimeFence in VPinMAME. If i remove that part from the core.vbs, then the startup is normal on all VPX versions.
I fail though to find out where exactly it hangs, cause the debugger just sends me into unknown ntdll territory.  :/

**Comment by toxieainc** [comment]
Do you maybe have Skip Pinball Startup enabled in PinMAME?

**Comment by toxieainc** [comment]
I still don't really get it, but if i replace the TimeFence snippet in core.vbs to skip the first setting of the TimeFence, then everything works:
```

	' If the Controller supports it, we synchronize the emulation with VPX physics & events for very low latency between them
	If HasTimeFence Then
		Dim t
		If HasPreciseGameTime Then
			t = PreciseGameTime
		Else
			t = GameTime / 1000.0
		End If
		If t > 3.0 Then
			Controller.TimeFence = t
		End If
	End If

```

**Comment by toxieainc** [comment]
@vbousquet Could you please carefully review my commit?
Cause i'm not certain for example about https://github.com/vpinball/pinmame/blob/f7ac3dfc2f6e9994fde5a265dbe2bf82d60a74bf/src/cpuexec.c#L970 and https://github.com/vpinball/pinmame/blob/f7ac3dfc2f6e9994fde5a265dbe2bf82d60a74bf/src/wpc/vpintf.c#L314

**Comment by vbousquet** [comment]
I have just reviewed the changes:
- First change is that when `timefence` is not set while expected, PinMame now consider that it has gone out of sync and should run on => it somewhat hides sync problems to the user by running the emulator while its driver app is out. Seems ok to me but does not solve the core problem that is to say the driver app not updating, or PinMame not handling well a paused state, or something else ? Beside it may result in the emulation going ahead of the driver app in some situations.
- Second change is that `vp_setTimeFence` starts with an initial offset corresponding to driver app clock. I'm a bit unsure on this one. I don't see why this would the right initial offset. In the end we rely on the cpu emulation capability to sync on the external clock. I guess the right way would to compute the exact offset (so based on the difference between emulation and driver app, needing to lock the emulation thread to read its clock) or just rely on the cpuexec syncing (which what it was supposed to do, but seemingly bugged).

My feeling is that the core bug is not really solved yet so I will reopen and have a deeper look

**Comment by vbousquet** [comment]
After having a deeper look, the dead lock was due to the PinMame not processing its messages when stalled.
I have just pushed a commit that fix this by performing needed screen update when master clock is stalled.
With this, I can't reproduce any of the dead lock we had

**Comment by toxieainc** [comment]
All still good, just confirmed with e46e5d27331c20eb95b1f3af9cefb7e5f7a6c6df and all the mentioned tables
(10.7.X and 10.8.X)
Thanks!

**Comment by vbousquet** [comment]
This bug happened to be a blessing since it allowed me to finally solve a long standing issue: I had occasional stutters with no apparent reasons. I had already searched for this and found some of the VBS Execute/ExecuteGlobal script function to trigger Microsoft Defender, so I removed them and it helped a lot (though, it broke PROC support...). But I still had the occasional stutters. 

Here I traced everything using MS Concurrency Visualiser (to identify the deadlock) and discovered that VPX would often stall waiting for VPM. Looking deeper it seems that the COM layer uses the message pump to handle things between VBS <-> VPM. Therefore VBS calls to VPM can stall until VPM process its message pump. The fix is pretty basic : just process the pump more frequently (`PeekMessage` is cheap enough). I implemented it in PinMame and as far as I can tell all the remaining stutters I had are now gone.
