### ISSUE TITLE
VPinballX_GL : incorrect monitor resolution/name and playfield screen

### ISSUE THREAD

**Issue by stojy** [vpinball/vpinball#357]
**Describe the bug**
Two related(?) issues with vpinball_gl regarding monitor selection and resolution.
- Starting table ingores the monitor selection and instead starts on the primary screen.,
- Resolutions and monitor names in the drop down box are incorrect.

**To Reproduce**

Incorrect resolution and name
1. Go to 'preferences - video options'.
2. Observe the monitor names are incorrect and also the resolutions.  Specifically in my example screenshot..
   1. The monitor resolution for monitor 3 is 4096 x 2160, i.e. not  6144 x 3240
   2. The samsung monitor is actually monitor 3, not 1.
       <img width="185" alt="image" src="https://user-images.githubusercontent.com/11408611/227754359-0cd09af8-1eba-4362-bef2-1ae7282fc2ce.png">
3. This appears to be a GL specific issue.  The exact same version non-GL has no issues.  [VPinballX-10.8.0-775-639a05c-Release-win-x64.zip](https://github.com/vpinball/vpinball/releases/download/v10.8.0-775-639a05c/VPinballX-10.8.0-775-639a05c-Release-win-x64.zip).
   <img width="211" alt="image" src="https://user-images.githubusercontent.com/11408611/227754650-28ecbb33-2b42-4e40-a4a0-5d0b15d0f73b.png">

Incorrect playfield usage
1. Select monitor 3 and start table.
2. Observe monitor 1 is used.
3. Similarly, change default monitor to 3 and observe monitor 3 is used.  Albeit it with a smaller sized table that isn't full screen, which is presumably a symptom of the resolution issue mentioned above.
4. Similarly, no issues with the non-GL version.

**Expected behavior**
Refer above.

**Screenshots**
Refer above.

**Crash dump**
n/a

**Versions**
 - [VPinballX_GL-10.8.0-775-639a05c-Release-win-x64.zip](https://github.com/vpinball/vpinball/releases/download/v10.8.0-775-639a05c/VPinballX_GL-10.8.0-775-639a05c-Release-win-x64.zip)
 - Windows version: 10
 - GPU and video settings if applicable: AMD Radeon RX 5700 XT, 23.3.2 (latest)

**Additional context**
- n/a

**Comment by vbousquet** [comment]
This should be solved in v1033+

Note that showing the display name instead of the graphic card is the intended behavior.

**Comment by stojy** [comment]
Nice one.  I'll test it out once 1033+ is released.

**Comment by vbousquet** [comment]
If you want, 1033 can be tested from the Action tab: https://github.com/vpinball/vpinball/actions
You will need a github account to download from there

**Comment by stojy** [comment]
I've tested 1033 and can confirm the issue with the wrong display monitor is fixed.

But the other two (related?) issues are still present..

1. Wrong monitor resolution shown as shown in red.  As per monitor setup below, I suspect the DPI from the default monitor (monitor 1) has been incorrectly assumed to be the same for monitor 3.
<img width="160" alt="image" src="https://user-images.githubusercontent.com/11408611/236627189-7c71569f-c9d1-422f-a5c4-0b1d62157a6e.png">

<img width="552" alt="image" src="https://user-images.githubusercontent.com/11408611/236627036-414becc2-0417-44b1-9440-45dc035fe4f7.png">

<img width="571" alt="image" src="https://user-images.githubusercontent.com/11408611/236627072-d1f29cd7-bf93-463c-91b0-8f051189efd5.png">

2. VPX is still starting the table on the default monitor (monitor 1) instead of the selected monitor 3.

Note, as mentioned earlier the non-GL VPX doesn't exhibit these issues.

**Comment by vbousquet** [comment]
I've wrapped another update (version 1036) that should solve this. Could you give it a try (I did and it fully worked on my cab) ?

**Comment by stojy** [comment]
The per monitor DPI looks good.  The resolutionsn are reported correctly now. 
![image](https://user-images.githubusercontent.com/11408611/236651841-d854a243-00cd-4c29-8825-7ab85377dc04.png)

However the last issue, where VPX is starting the table on the default monitor instead of the selected monitor, still doesn't work. 

I could raise this as a separate issue if you'd prefer?  i.e. if it's unrelated to the monitor name and DPI issues you've fixed.

**Comment by vbousquet** [comment]
This part of the OpenGL version was in fact completely broken. I rewrote it and I hope it should be good in v1045 (at least it seems good on my end). Could you give it a try ?

**Comment by stojy** [comment]
It correctly starts on the specified screen now :)  For myself (and presumably others) this was the biggest issue preventing the use of the GL version with my cabinet setup, so I'm happy it's now fixed.

Possibly related to the OpenGL driver, I did notice that it may be under reporting the FPS?  I say this because on my setup it's reporting around 50-55fps despite the GPU sittting pretty flat at ~80% usage (and CPUI around 50%) with no obvious jerkiness/frame-drops during game play.  If it's not a known issue with the GL version, then I'll play it with a little more and report it as a separate github issue.

Thanks for all your hardwork.
