### ISSUE TITLE
Texture issues Monster Bash VPW

### ISSUE THREAD

**Issue by Jayhay89** [vpinball/vpinball#683]
Texture issues on latest 10.8 build (see screenshots below)

https://vpuniverse.com/files/file/9091-monster-bash-williams-1998-vpwmod/

![](https://cdn.discordapp.com/attachments/783862859942723605/1142961242412154940/image.png)

![](https://cdn.discordapp.com/attachments/783862859942723605/1142961242693181450/image.png)

Screenshots below with the table running on 10.7 (rendering correctly)

![image](https://github.com/vpinball/vpinball/assets/86264211/9f4d7cb9-e091-46f2-bd5a-c64b8e1dd0ab)

![image](https://github.com/vpinball/vpinball/assets/86264211/9c48f0c4-7f99-4f92-aeef-945d654f1920)

 - VPX: 10.8 (rev 1360)
 - DX
 - Windows 11
 - Screen Space Reflections - OFF
 - AO - OFF

**Comment by Jayhay89** [comment]
Hi @vbousquet 
This issue still resides in the latest build fc71d22

**Comment by vbousquet** [comment]
Just retested and it is solved for me in build 1367 (for this table as well as others). Did you update your shaders ?

**Comment by Jayhay89** [comment]
@vbousquet 
How do you go about updating the shaders?

**Comment by vbousquet** [comment]
The shaders is the folder for OpenGL builds. There is non for DirectX.

I did some more testing following your comment. It appears that there are at least 2 problems here:
- the one I already solved with the GeometricOpacity and back lighting,
- the normal mapping, using tangent space, which is not working on OpenGL. On DirectX it is supposed to work (it looks ok to me)

**Comment by Jayhay89** [comment]
@vbousquet 
Thanks for the info :-)
Yes, just tested in OGL and similar issues to DirectX, but it effects different table objects/textures. 
I've rebooted, deleted texture cache etc, but Direct X is still displaying this issue for me

**Comment by MydknyteStyrm** [comment]
I am experiencing the same issue on the latest build of 10.8

**Comment by Jayhay89** [comment]
@vbousquet This isn't resolved for me. Still the same rendering issues on 10.8 DX and OpenGL

**Comment by vbousquet** [comment]
Could you post some screenshots using latest builds ? On my side it is solved but this bugs already had a hidden bug behind him, so perhaps a third one is there too ?

**Comment by Jayhay89** [comment]
@vbousquet 
![image](https://github.com/vpinball/vpinball/assets/86264211/8b7bffeb-25b2-4c6d-9879-c46db52c1575)

**Comment by vbousquet** [comment]
Ok. THis si likely invalid backlighting on a normal mapped part. I will have a look

**Comment by dacstyle** [comment]
I also have a problem with the bride face and dracula shadow.

I'm using GL 64 1394

![Screenshot_20230903_163211_Facebook](https://github.com/vpinball/vpinball/assets/119076983/f4b0cb0c-daef-4078-bacb-c19da98eb055)

**Comment by vbousquet** [comment]
This took me a while because there were quite a few bugs in that one. I have pushed a commit that fix this bug, but not entirely:
- there was a bug in the rendering code that would cause overflow of shading => this is fixed
- there was a bug in the rendering that lead to wrong normals for normal mapped parts, hence wrong shading => this is fixed as well
- the table rely on a bug of VPX which is fixed in 10.8, that is to say that the texture transparency would be ignored if the material opacity is equal to 1 (that's the reason lots of table have materials with opacity of 0.99999, to work around this bug). Here frankenstein has a transaprent texture, with lighting from behind activated. The old versions of VPX would not process this transparency, but now it is processed. To put it short, this is a table bug, not a VPX bug. The fix is very easy: just set the disable lighting from behind to 1 for the arms and chest of frankenstien

**Comment by dacstyle** [comment]
Thanks, the bride problem was solved, and I fixed the Frankenstein light with your suggestion. 

But I found another rare thing, there is a la light in the shape of Igor that is not moving with Igor when you change the POV.

The same is occurring with the bride, check the following screenshot.

Vpx 10.8 GL 64 1412
![Screenshot_20230906_010151_WhatsApp](https://github.com/vpinball/vpinball/assets/119076983/6b036ed8-acf7-4316-bd0d-9f2e053d469a)

**Comment by toxieainc** [comment]
@dacstyle Could you please open this as a new issue? Otherwise it will get lost in here.

**Comment by vbousquet** [comment]
I have been trying to reproduce without any luck. Could you post more details, use a screenshot instead of a photo (to avoid external reflections from real world) ?

**Comment by dacstyle** [comment]
sure, here is the screenshot, the system do not allow me to upload the pov file so you can see that light
![Screenshot_2](https://github.com/vpinball/vpinball/assets/119076983/623b47bb-428b-45ff-ae6a-09a586de5207)

**Comment by vbousquet** [comment]
Renaming your pov filt to .txt will allow to upload, also the vpinballx.ini would help

**Comment by dacstyle** [comment]
both uploaded

[Monster Bash (Williams 1998).txt](https://github.com/vpinball/vpinball/files/12571234/Monster.Bash.Williams.1998.txt)
[VPinballX.txt](https://github.com/vpinball/vpinball/files/12571239/VPinballX.txt)

**Comment by vbousquet** [comment]
@dacstyle Latest builds (from action tab) have some more fixes that should improve the bacjward compatibility for this table. Could you have a look and tell me if this is solved ? Note that if you have edited the table and saved it (marking it as a 10.8 table), the fix won't apply, so it would be better to test from a freshly downloaded version of the table

**Comment by dacstyle** [comment]
tested with 1467 and re downloading the table, the issue still persist

**Comment by vbousquet** [comment]
I have pushed a few fixes to the rendering engine. Does this bug still appear for you (I can't reproduce on my side) ?

**Comment by dacstyle** [comment]
Tested on 1604, re downloading the table, the issue persist

**Comment by vbousquet** [comment]
Just had a deeper look into this bug and it appears that in the end, this is not a bug. The table uses precomputed flasher for fake lighting that only matches if the POV is kept untouched. Here it is the flasher named `igorflash` that ends up being offcentered when changing the POV
